# Generated by Django 6.0.4 on 2026-06-12 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_booking_created_at_booking_metode_pembayaran_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('merek', models.CharField(max_length=100)),
                ('transmisi', models.CharField(max_length=50)),
                ('kapasitas', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='bank_pembayaran',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='metode_pembayaran',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Konfirmasi'), ('disetujui', 'Pembayaran Disetujui'), ('ditolak', 'Pembayaran Ditolak')], default='menunggu', max_length=30),
        ),
    ]
