# Generated by Django 6.0.4 on 2026-06-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_car_booking_bank_pembayaran_booking_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='merek',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='harga',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='gambar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='kapasitas',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='transmisi',
            new_name='transmission',
        ),
    ]
