# Generated by Django 6.0.4 on 2026-06-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rename_merek_car_brand_rename_harga_car_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Konfirmasi'), ('diproses', 'Sedang Diproses'), ('selesai', 'Berhasil'), ('ditolak', 'Ditolak')], default='menunggu', max_length=30),
        ),
    ]
