# Generated by Django 6.0.6 on 2026-06-25 14:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_booking_car_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bukti_transfer',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_transfer/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='kode_unik',
            field=models.IntegerField(default=0, help_text='Kode unik 3 angka untuk membedakan pembayaran.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_bayar',
            field=models.IntegerField(default=0, help_text='Total harga sewa + kode unik.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profile/foto/')),
                ('nama_lengkap', models.CharField(blank=True, max_length=150)),
                ('no_hp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Nomor HP harus berisi angka dan minimal 10 digit.', regex='^[0-9+\\-\\s]{10,20}$')])),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('nik_ktp', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NIK/KTP harus 16 digit angka.', regex='^[0-9]{16}$')])),
                ('foto_ktp', models.ImageField(blank=True, null=True, upload_to='profile/ktp/')),
                ('nomor_sim_a', models.CharField(blank=True, max_length=30)),
                ('masa_berlaku_sim', models.DateField(blank=True, null=True)),
                ('foto_sim_a', models.ImageField(blank=True, null=True, upload_to='profile/sim/')),
                ('alamat_lengkap', models.TextField(blank=True)),
                ('kota', models.CharField(blank=True, max_length=100)),
                ('provinsi', models.CharField(blank=True, max_length=100)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('kontak_darurat_nama', models.CharField(blank=True, max_length=150)),
                ('kontak_darurat_no_hp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Nomor kontak darurat harus berisi angka dan minimal 10 digit.', regex='^[0-9+\\-\\s]{10,20}$')])),
                ('kontak_darurat_hubungan', models.CharField(blank=True, help_text='Contoh: Orang tua, saudara, pasangan, teman.', max_length=100)),
                ('status_verifikasi', models.CharField(choices=[('belum_lengkap', 'Belum Lengkap'), ('menunggu', 'Menunggu Verifikasi'), ('terverifikasi', 'Terverifikasi'), ('ditolak', 'Ditolak')], default='belum_lengkap', max_length=20)),
                ('catatan_admin', models.TextField(blank=True)),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_diverifikasi', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil User',
                'verbose_name_plural': 'Profil User',
            },
        ),
    ]
