# Generated by Django 6.0.6 on 2026-06-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_booking_bukti_transfer_booking_kode_unik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stock_dikurangi',
            field=models.BooleanField(default=False, help_text='Menandai apakah stok mobil sudah dikurangi untuk booking ini.'),
        ),
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah unit mobil yang tersedia untuk disewa.'),
        ),
    ]
