# Generated by Django 6.0.6 on 2026-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_booking_stock_dikurangi_car_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ai_catatan_pembayaran',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ai_nominal_terdeteksi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ai_raw_response',
            field=models.TextField(blank=True, help_text='Respon mentah AI.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ai_status_pembayaran',
            field=models.CharField(choices=[('pending', 'Belum Diperiksa'), ('jelas', 'Jelas'), ('buram', 'Buram'), ('tidak_valid', 'Tidak Valid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_catatan_ktp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_catatan_sim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_status_ktp',
            field=models.CharField(choices=[('pending', 'Belum Diperiksa'), ('jelas', 'Jelas'), ('buram', 'Buram'), ('tidak_valid', 'Tidak Valid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_status_sim',
            field=models.CharField(choices=[('pending', 'Belum Diperiksa'), ('jelas', 'Jelas'), ('buram', 'Buram'), ('tidak_valid', 'Tidak Valid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='kode_unik',
            field=models.IntegerField(default=0, help_text='Kode unik 3 angka.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stock_dikurangi',
            field=models.BooleanField(default=False, help_text='Menandai apakah stok mobil sudah dikurangi.'),
        ),
    ]
